### ISSUE TITLE
system.exception on DateTimeExtensions.FromIso8601

### ISSUE THREAD

**Issue by poundy** [mweimer/Json.NetMF#6]
Installed from nuget.
I have tested this code block and get an exception from the extension method DateTimeExtensions.FromIso8601().  

    #### Exception System.Exception - 0x00000000 (1) ####
    #### Message: 
    #### System.Convert::ToInt64 [IP: 00af] ####
    #### System.Convert::ToInt32 [IP: 0011] ####
    #### Json.NETMF.DateTimeExtensions::FromIso8601 [IP: 0083] ####
    #### testJSONParse.Program::Main [IP: 0017] ####

Test:
            DateTime nowTime = DateTime.Now;
            JsonSerializer dataSerializer = new JsonSerializer(DateTimeFormat.ISO8601);
            string jsonString = dataSerializer.Serialize(nowTime);
            DateTime convertTime = DateTimeExtensions.FromIso8601(jsonString); // exception
            Debug.Print("Converted: " + jsonString);

If I attempt to step into the files downloaded from Github I get told the source and nuget files are different, maybe a different issue, but the exception seems to be thrown by the parsing of YEAR which seems to have a leading quote mark.  From JSON visualizer the text seems formed correct:
[JSON]: "22/04/2015 10:18:54 PM"

I can't be sure if the date.Split() is incomplete, or if the leading quote isn't working, or if there's some other issue. Any thoughts ?

**Comment by mweimer** [comment]
Hi, 

The string you are trying to convert there does not meet the ISO 8601 standard. A date-time string from ISO 8601 has no space and is separated by the character 'Z'. Also, the date must be formatted has year-month-day. Some examples for your date/time would be '2015-04-22T10:18:54+00:00' or '2015-04-22T10:18:54Z'. Currently, this project only has methods to convert 2 types of date-time formats, it would seem your string is not either. If you are the one specifying the date-time format for your data, you could change it to one of the 2 this project supports. Outside of that, you will probably have to write your own date-time conversion method.

**Comment by mweimer** [comment]
Sorry, I misinterpreted your issue with my previous comment. It looks there is an issue here with you code snippet. The serializer does seems to be throwing in an extra double-quote character when serializing the date-time to a string. I will fix this right away, thanks!.

**Comment by mweimer** [comment]
Hi,

So I reviewed this some more and did some testing, and the code is actually behaving correctly per the JSON spec. When you serialize a DateTime into a JSON string, it must be in a string enclosed in escaped double-quotes. So, your example became "\"2015-04-22T22:18:54.000Z\"". This is a correctly formatted DateTime in JSON. The datetime conversion utility method is expecting a normal date-time string, not formatted in JSON. So it needs just: "2015-04-22T22:18:54.000Z". In order to achieve this in your code snippet you need to deserialize the serialized object so you need to add a line of code.
```c#
 DateTime nowTime = DateTime.Now;
 JsonSerializer dataSerializer = new JsonSerializer(DateTimeFormat.ISO8601);
 string jsonString = dataSerializer.Serialize(nowTime);
 string deserializedJsonString = (string)dataSerializer.Deserialize(jsonString);
 DateTime convertTime = DateTimeExtensions.FromIso8601(deserializedJsonString); 
 Debug.Print("Converted: " + jsonString);
```

**Comment by poundy** [comment]
Awesome - the example deserializes into the hashtable, which is the difference that my scenario didn't, and the relevance of that didn't strike me. The interesting thing is that VS's JSON visualizer handled it fine when looking at the local variable, so it must cater for stripping the quotes. 

I am hitting another issue but think this one will be harder to figure out - still working through it and will report back separately if I think there's something you can do. I am sending JSON objects over a 2.4ghz wireless link and when I get transmission issues, I always end up with data inconsistencies. which can lead to repeated keys that probably don't get hashtabled too well :)
